import { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/components/Banner.module.scss";
import Header from "./Header.component";

interface LayoutProps {
  children: any;
}

const Layout: NextPage<LayoutProps> = (props: LayoutProps) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <main className="container mx-auto">
          <Header/>
          {props.children}
        </main>
      </div>
    </>
  );
}

Layout.getInitialProps
export default Layout;